name = "cfw-bun-hono-drizzle"
compatibility_date = "2024-08-28"

[vars]
MY_VAR = "MY Best Love Girl Mandy"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cfw-bun-hono-drizzle-d1"
database_id = "4ce62718-7b9a-4d8f-ad8a-740882958516"
migrations_dir = "drizzle/migrations"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

